name: ${plugin.name}
version: ${project.version}
main: ${plugin.main.classpath}
api-version: 1.15
author: Fr33styler
softdepend:
  - WorldLoader
  - MultiWorld
  - Multiverse-Core
commands:
  Spawn:
    description: The command which teleports the player to the spawn.
  SetSpawn:
    description: The command to set always spawn.